force-app/main/default/objects/reCAPTCHA_Keys__c/reCAPTCHA_Keys__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>reCAPTCHA Keys</label>
</CustomObject>

force-app/main/default/objects/reCAPTCHA_Keys__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <label>Secret Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/reCAPTCHA_Keys__c/fields/Site_Key__c.field-meta.xml
<CustomField>
    <fullName>Site_Key__c</fullName>
    <label>Site Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GoogleRecaptchaControllerTest.cls
@IsTest 
private class GoogleRecaptchaControllerTest {

    @TestSetup
    static void makeData(){
        
        insert new reCAPTCHA_Keys__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            Site_Key__c = 'XXX',
            Secret_Key__c = 'XXX'
        );
    }

    @IsTest
    static void testVerificationSuccess() {

        // Retrieve unique key, used for server side validation
        String siteKey = GoogleRecaptchaController.getSiteKey();
        String uniqueKey = GoogleRecaptchaController.getUniqueKey();

        Test.setMock(
            HttpCalloutMock.class,
            new NSS_HttpMock(
                200,
                '{"success": true}'
            )
        );

        Test.startTest();

        // Run validation
        Boolean isVerified = GoogleRecaptchaController.isVerified('XXX', uniqueKey);

        // Assert validation
        system.assert(
            GoogleRecaptchaController.validateRecaptcha(uniqueKey),
            'Google reCAPTCHA should be verfiied.'
        );

        Test.stopTest();
    }

    @IsTest
    static void testVerificationError() {

        // Retrieve unique key, used for server side validation
        String siteKey = GoogleRecaptchaController.getSiteKey();
        String uniqueKey = GoogleRecaptchaController.getUniqueKey();

        Test.setMock(
            HttpCalloutMock.class,
            new NSS_HttpMock(
                200,
                '{"success": false, "error-codes": "Error"}'
            )
        );

        Boolean hasError = false

        Test.startTest();

        try {

            // Run validation
            Boolean isVerified = GoogleRecaptchaController.isVerified('XXX', uniqueKey);
        }
        catch (AuraHandledException ex) {

            hasError = true;
        }

        Test.stopTest();

        system.assert(hasError, 'Error should be thrown after failing validation');
    }
    
}